### ISSUE TITLE
Generate thumbnails dynamically

### ISSUE THREAD

**Issue by dvaJi** [dvaJi/ReaderFront#111]
https://malcoded.com/posts/nodejs-image-resize-express-sharp  

**TODO:**
- [ ] Add route to API
- [ ] Generate thumb if it doesn't exist
- [ ] if lowQuality param is true, it should generate and return a webp image
- [ ] Check if browser accept webp with [this component](https://github.com/DonRai/react-image-webp)

_URL should be: domain.com/images/dir_to_image/image.jpg?height=200&lowQuality=true_
