### ISSUE TITLE
Filtros avanzados para Series

### ISSUE THREAD

**Issue by dvaJi** [dvaJi/ReaderFront#58]
Actualmente sólo se puede filtrar por nombre, la idea es poder dar un filtro más personalizado con las siguientes características:

- [ ] Filtrar por géneros (https://github.com/dvaJi/ReaderFront/issues/57)
- [ ] Filtrar por estado serie (https://github.com/dvaJi/ReaderFront/issues/15)
- [ ] Filtrar por categoría (https://github.com/dvaJi/ReaderFront/issues/56)
- [ ] Ordenar por Nombre (ASC/DESC) y Última actualización (ASC/DESC)
